### PR TITLE
Fix issue #60 on OutputFormat options

### LINKED ISSUE #60: [R66] the formatting of the output of the send commands is broken
It seems there is no support for the formatting options of the send comands: `-xml`, `-json`, `-property`, etc.

```
➜ ./bin/waarp-r66client.sh client1 send -property -file ./file.dat -to server1 -rule push
usage: Transfer
 -block <arg>   Specify the block size
 -delay <arg>   Specify the delay time as an epoch time or '+' a delay in
                ms
 -file <arg>    Specify the file path to operate on
 -id <arg>      Specify the id of transfer
 -info <arg>    Specify the transfer information
 -logWarn       Specify to log final result as Warn if OK
 -md5           Specify the option to have a hash computed for the
                transfer
 -nofollow      Specify if the transfer should not integrate a FOLLOW id
 -nolog         Specify to not log anything included database once the
                transfer is done
 -notlogWarn    Specify to log final result as Info if OK
 -rule <arg>    Specify the Rule
 -start <arg>   Specify the start time as yyyyMMddHHmmss
 -to <arg>      Specify the requested Host
Wrong initialization
```

### LINKED ISSUE #78: The output of client does not escape values according to the target format
Some output values can contain XML-like data. 
When we ask the command to format the output in XML with `-xml`, this produce a valid XML structure, but it does not match the intent.

For example, with the output for a failed transfer, I have the following XML (the formatting has been added by me to highlight what I mean):

```xml
<xml>
  <command>DirectTransfer</command>
  <args>etc/conf.d/server2/client.xml -file world.txt -to server1 -rule error -xml </args>
  <status>2</status>
  <statusTxt>Transfer in status: FAILED with no Transfer Id</statusTxt>
  <remote>server1</remote>
  <error>
    ErrorPacket:(3:E) PreTask in error: Runner is failed: 
    <STATUS>-1</STATUS>
    <ERROR>will fail </ERROR>
  </error>
</xml>
```

Though it is valid, `<STATUS>` and `<ERROR>` are part of `<error>` and not tags of the main XML document.
The output should use entity refs to protect the content of the `<error>` message:

```xml
<xml>
  <command>DirectTransfer</command>
  <args>etc/conf.d/server2/client.xml -file world.txt -to server1 -rule error -xml </args>
  <status>2</status>
  <statusTxt>Transfer in status: FAILED with no Transfer Id</statusTxt>
  <remote>server1</remote>
  <error>
    ErrorPacket:(3:E) PreTask in error: Runner is failed: 
    &lt;STATUS&gt;-1&lt;/STATUS&gt;
    &lt;ERROR&gt;will fail &lt;/ERROR&gt;
  </error>
</xml>
```

*edit:*
I realised by reviewing #67 that the same problem exists for other output formats.

Here is an example with `-csv`. The culprits are the semicolon (`;`) between "will" and "fail" and the new line which are not protected, hence adding an extra column in the first line, and a second record in the second line:

```csv
command;args;status;statusTxt;remote;error
DirectTransfer;etc/conf.d/server2/client.xml -file world.txt -to server1 -rule error -csv ;2;Transfer in status: FAILED with no Transfer Id;server1;ErrorPacket:(3:E) PreTask in error: Runner is failed: <STATUS>-1</STATUS><ERROR>will ;fail
always
```

The output should be:

```csv
command;args;status;statusTxt;remote;error
DirectTransfer;etc/conf.d/server2/client.xml -file world.txt -to server1 -rule error -csv ;2;Transfer in status: FAILED with no Transfer Id;server1;"ErrorPacket:(3:E) PreTask in error: Runner is failed: <STATUS>-1</STATUS><ERROR>will ;fail
always"
```

### PR DESCRIPTION
**Pull request by fredericBregier**
OutputFormat options were lost in last release. This fixes the issue #60.

### CODE REVIEW

**Review by bcarlin — APPROVED** [review]

**Comment by fredericBregier** [comment]
See changes for #78

File: WaarpR66/src/main/java/org/waarp/openr66/client/utils/OutputFormat.java [hunk 1]
```diff
@@ -246,7 +283,9 @@ public String toString(OUTPUTFORMAT format) {
               next = true;
             }
             builderKeys.append(entry.getKey());
-            builderValues.append(entry.getValue());
+            String value = entry.getValue().toString();
+            value = value.replace(';', ',');
+            builderValues.append(value);
```
Comment (bcarlin) [inline WaarpR66/src/main/java/org/waarp/openr66/client/utils/OutputFormat.java]: This handles the `;` case at the cost of modifying data, but does not address other cases like `\n`.
A [common way](https://en.wikipedia.org/wiki/Comma-separated_values) to do that is to surround values with `"`. 
This is supported by Excel, LibreOffice Calc, etc.

This seems more resilient :
```java
value = value.replace('"', '""');
builderValues.append('"').append(value).append('"');
```

File: WaarpR66/src/main/java/org/waarp/openr66/client/utils/OutputFormat.java [hunk 2]
```diff
@@ -286,8 +327,11 @@ public String toString(OUTPUTFORMAT format) {
               });
           final StringBuilder builder = new StringBuilder("<xml>");
           for (final Entry<String, Object> entry : map.entrySet()) {
+            String value = entry.getValue().toString();
+            value = value.replace('<', '[');
+            value = value.replace('>', ']');
```
Comment (bcarlin) [inline WaarpR66/src/main/java/org/waarp/openr66/client/utils/OutputFormat.java]: I think it is best when possible, not to change the values.
In XML, two chars must not be in the content: `<` and `&`.

This is more resilient:
```java
value = value.replace("&", "&amp;").replace("<", "&lt;");
```

**Review by bcarlin — CHANGES_REQUESTED** [review]

File: WaarpR66/src/main/java/org/waarp/openr66/client/utils/OutputFormat.java (hunk 1 above)
Comment (fredericBregier) [reply WaarpR66/src/main/java/org/waarp/openr66/client/utils/OutputFormat.java]: First doest ot work (single character, not string).
Second would imply that all value will be surrounded by `"`, which is not potentially what we want (number are not String).
So I propose:
- common clean = `\n` or `\r` replaced by ` ` 
- if there is a `;`, then surround by `"` as you requested (so only if needed)

File: WaarpR66/src/main/java/org/waarp/openr66/client/utils/OutputFormat.java (hunk 2 above)
Comment (fredericBregier) [reply WaarpR66/src/main/java/org/waarp/openr66/client/utils/OutputFormat.java]: I understand, but it seems very ugly for end users... Worst than replacing unalowed characters (need to undecode while not really undecodable since simple String).
So I would propose to replace `<` and `>` by still `[` and `]` and replace `&` by `:` (or something else if better)
Still parsable...

File: WaarpR66/src/main/java/org/waarp/openr66/client/utils/OutputFormat.java (hunk 1 above)
Comment (fredericBregier) [reply WaarpR66/src/main/java/org/waarp/openr66/client/utils/OutputFormat.java]: See proposal and tests

File: WaarpR66/src/main/java/org/waarp/openr66/client/utils/OutputFormat.java (hunk 2 above)
Comment (fredericBregier) [reply WaarpR66/src/main/java/org/waarp/openr66/client/utils/OutputFormat.java]: See proposal and tests

**Comment by fredericBregier** [comment]
@bcarlin see proposals and tests

**Review by bcarlin — APPROVED** [review]
